# SPDX-License-Identifier: BSD-3-Clause
namespace: moreati
name: test_artifacts
version: 0.1.0
readme: README.md
authors:
  - Alex Willmer <alex@moreati.org.uk>
description:
  Modules, module utils and other plugins for use in unit and integration tests.
license:
  - BSD-3-Clause
repository: http://github.com/moreati/ansible-test_artifacts
issues: http://github.com/moreati/ansible-test_artifacts/issues

build_ignore:
  - '.gitignore'
  - '.venv'
  - '*.tar.gz'
